#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

runApplication blockMesh

N_PROCS=$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}')
[ -z "$N_PROCS" ] && N_PROCS=4 # if N_PROCS not found, set it to 4

foamDictionary system/decomposeParDict -entry numberOfSubdomains -set $N_PROCS

rm -rf 0
cp -r 0.orig 0

runApplication decomposePar
runParallel "$(getApplication)"
